import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { invoke } from "@tauri-apps/api/tauri";
import { useState } from "react";

const Home: NextPage = () => {
  const [result, setResult] = useState("");
  const [input, setInput] = useState("");

  async function execCurrent() {
    setResult(await invoke("eval", { code: input }));
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{result}</h1>
        <input type="text" onChange={(e) => setInput(e.target.value)} />

        <button onClick={execCurrent}>click me</button>
      </main>
    </div>
  );
};

export default Home;
